### ISSUE TITLE
Create a production-ready docker image for OpenSPP

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-api#90]

**Comment by atelal** [comment]
Doodba stands for Docker Odoo Base, and it is a highly opinionated image ready to put [Odoo](https://www.odoo.com/) inside it, but without Odoo.
It contains a lot of tools to make the process easier for the developers. It has multiple tools like [click-odoo-update](https://github.com/acsone/click-odoo-contrib).
There's also [git-aggregator](https://github.com/acsone/git-aggregator).

Doodba also added software like nano, vim, ffmpeg and chromium. They may not be required in a production environment.

The base image will be for the community edition of odoo, another image will be created for the enterprise edition of odoo. For the enterprise version, it will be possible to copy the source code of the [repository](git clone https://github.com/odoo/enterprise.git) to make it become "enterprise". The documentation is available [here](https://www.odoo.com/documentation/15.0/administration/install/source.html#fetch-the-sources)

**Comment by atelal** [comment]
As seen with Jeremy, we will base the image on python:debian-slim.

**Comment by atelal** [comment]
Hello,
I've found this [image](https://hub.docker.com/r/bitnami/odoo)
It is maintained by bitnami (and backed by VMware

Here's the [source code](https://github.com/bitnami/containers/tree/main/bitnami/odoo)

`All our images are based on minideb -a minimalist Debian based container image that gives you a small base container image and the familiarity of a leading Linux distribution- or scratch -an explicitly empty image-.
`
For info, debian slim is a bit bigger.

**Comment by atelal** [comment]
For now here are the different images tested:

```
ubuntu-odoo                    latest        704751470197        12 seconds ago        1.64GB
odoo-debian-slim               latest        a12566673d94        About a minute ago    1.77GB
python-debian-slim-odoo        latest        fde383dad5ff        8 minutes ago         1.82GB
```

In this base Dockerfiles, it will retrieve the odoo source code and install all the dependencies needed.

For faster building, I modified the ubuntu repositories in /etc/apt/sources.list to point to the following mirror:
http://mirrors.nipa.cloud/ubuntu/

The full list is available [here](https://launchpad.net/ubuntu/+archivemirrors)

After creating this image. I will use doodba in the multi-stage build process in order to have all the things we need.
I will need to check on the team to know what are the dependencies needed for the project.

**Comment by atelal** [comment]
Follow the best practices here: https://opensource.com/article/20/5/optimize-container-builds

**Comment by atelal** [comment]
First iteration available on this branch: `change_odoo_base_image`
